---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  selector:
    matchLabels:
      app: python-falsk-project
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: python-falsk-project
    spec:
      containers:
      - name: python-falsk-project
        image: 251991/python-task
        imagePullPolicy: Always
        ports:
        - containerPort: 5000